name: CMake Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake make gcc
    - name: Configure CMake
      run: cmake -S . -B build
    - name: Build
      run: cmake --build build
    - name: Run tests
      run: |
        cd build
        ctest || (echo 'No tests found, running binary with data.csv' && ../random-forest data.csv)
